### ISSUE TITLE
Add-opened button

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/synw_favorites#5]
Maybe button no need; command does it

**Comment by kvichans** [comment]
Команда не нужна - достаточно кнопки в диалоге

**Comment by Alexey-T** [comment]
команду, если нет хоткея, вызвать быстрее.

**Comment by kvichans** [comment]
Есть пользователи (например, я), которым команда не нужна

**Comment by Alexey-T** [comment]
Ok..
